-- CreateTable
CREATE TABLE "CanteenSettings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "openMinute" INTEGER NOT NULL DEFAULT 480,
    "closeMinute" INTEGER NOT NULL DEFAULT 1260,
    "slotMinutes" INTEGER NOT NULL DEFAULT 15,
    "slotCapacity" INTEGER NOT NULL DEFAULT 20,
    "acceptingOrders" BOOLEAN NOT NULL DEFAULT true,
    "taxBasisPoints" INTEGER NOT NULL DEFAULT 500
);
